from collections.abc import Iterator
from pathlib import Path
import time
from typing import Optional
import psycopg
from pydantic_settings import BaseSettings, SettingsConfigDict
from psycopg.rows import dict_row


class DatabaseSettings(BaseSettings):
    host: str
    port: int = 5432
    database: str
    user: str
    password: str

    model_config = SettingsConfigDict(
        env_file=Path(__file__).resolve().parents[2] / ".env",
        env_prefix="",
        case_sensitive=True,
        extra="ignore",
    )


settings = DatabaseSettings()


def get_connection() -> psycopg.Connection:
    return psycopg.connect(
        host=settings.host,
        port=settings.port,
        dbname=settings.database,
        user=settings.user,
        password=settings.password,
        row_factory=dict_row,
    )


# def initialize_database() -> None:
#     with get_connection() as connection:
#         with connection.cursor() as cursor:
#             # cursor.execute(
#             #     """
#             #     create table if not exists services (
#             #         serviceid integer generated by default as identity primary key,
#             #         name text not null,
#             #         duration_minutes integer not null check (duration_minutes > 0),
#             #         price numeric(10, 2) not null check (price >= 0),
#             #         active boolean not null default true
#             #     )
#             #     """
#             # )
#             cursor.execute("select count(*) as total from services")
#             # if cursor.fetchone()["total"] == 0:
#             #     cursor.executemany(
#             #         """
#             #         insert into services (name, duration_minutes, price)
#             #         values (%s, %s, %s)
#             #         """,
#             #         [
#             #             (8,"Corte clásico", 45, 15.00),
#             #             (9,"Corte y barba", 60, 22.00),
#             #         ],
#             #     )


def list_active_services() -> Iterator[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select s.serviceid, s.name, s.duration, s.price::float8 as price, s.status, s.img_url
                from services s
                where s.status =true
                order by serviceid
                """
            )
            yield from cursor.fetchall()

def insert_service(name:str, duration:int, price:float,status:bool, img_url: Optional[str] = None) -> None:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                insert into services (name, duration, price, status, img_url)
                values (%s,%s, %s,%s,%s)
                """,
                (name, duration, price, status, img_url),
            )

def insert_product(name:str, code:str, stock:str, price:float, status:str,description:str, img_url: Optional[str] = None) -> None:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                insert into product (name, code, stock, price, status, description, img_url)
                values (%s,%s, %s,%s,%s,%s,%s)
                """,
                (name, code, stock, price, status, description, img_url),
            )

def insert_emloyee(dni:str, name:str, last_name:str, email:str, address:str, phone:str,hire_date:str) -> None:
    personid = None
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                insert into person(dni,name, last_name, email, address, phone)
                values (%s,%s, %s,%s, %s,%s) returning personid
                """,
                (dni,name, last_name, email, address, phone),
            )
            personid = cursor.fetchone()["personid"]
            cursor.execute(
                """
                insert into employee(hire_date, personid)
                values (%s, %s)
                """,
                (hire_date, personid),
            )

def insert_client(dni:str, name:str, last_name:str, email:str, address:str, phone:str,ruc:str) -> None:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                insert into person(dni,name, last_name, email, address, phone)
                values (%s,%s, %s,%s, %s,%s) returning personid
                """,
                (dni,name, last_name, email, address, phone),
            )
            personid = cursor.fetchone()["personid"]
            cursor.execute(
                """
                insert into client(ruc, personid)
                values (%s, %s)
                """,
                (ruc, personid),
            )

def list_active_clients() -> Iterator[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select c.clientid, c.ruc, p.personid, p.dni, p.name, p.last_name,
                       p.email, p.address, p.phone
                from client c
                join person p on p.personid = c.personid
                where p.status <> 'I'
                order by p.last_name, p.name, c.clientid
                """
            )
            yield from cursor.fetchall()


def list_products() -> Iterator[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select productid, name, code, stock, price::float8 as price,
                       created_at, status, description
                from product
                where status <> 'I'
                order by productid
                """
            )
            yield from cursor.fetchall()


def find_product(productid: int) -> Optional[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select productid, name, code, stock, price::float8 as price,
                       created_at, status, description
                from product
                where productid = %s
                """,
                (productid,),
            )
            return cursor.fetchone()


def update_product(productid: int, name: str, code: str, stock: str, price: float, description: str) -> bool:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                update product
                set name = %s, code = %s, stock = %s, price = %s, description = %s
                where productid = %s and status <> 'I'
                """,
                (name, code, stock, price, description, productid),
            )
            return cursor.rowcount > 0


def deactivate_product(productid: int) -> bool:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute("update product set status = 'I' where productid = %s", (productid,))
            return cursor.rowcount > 0


def list_all_services() -> Iterator[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select serviceid, name, duration, price::float8 as price, status
                from services
                where status = true
                order by serviceid
                """
            )
            yield from cursor.fetchall()


def find_service(serviceid: int) -> Optional[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select serviceid, name, duration, price::float8 as price, status
                from services
                where serviceid = %s
                """,
                (serviceid,),
            )
            return cursor.fetchone()


def update_service(serviceid: int, name: str, duration: int, price: float, img_url: Optional[str]) -> bool:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                update services
                set name = %s, duration = %s, price = %s, img_url = %s
                where serviceid = %s and status = true
                """,
                (name, duration, price, img_url, serviceid),
            )
            return cursor.rowcount > 0


def deactivate_service(serviceid: int) -> bool:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute("update services set status = false where serviceid = %s", (serviceid,))
            return cursor.rowcount > 0


def find_person(personid: int) -> Optional[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select personid, dni, name, last_name, email, address, phone
                from person
                where personid = %s
                """,
                (personid,),
            )
            return cursor.fetchone()


def update_person(personid: int, dni: str, name: str, last_name: str, email: str, address: str, phone: str) -> bool:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                update person
                set dni = %s, name = %s, last_name = %s, email = %s, address = %s, phone = %s
                where personid = %s
                """,
                (dni, name, last_name, email, address, phone, personid),
            )
            return cursor.rowcount > 0


def deactivate_person(personid: int) -> bool:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute("update person set status = 'I' where personid = %s", (personid,))
            return cursor.rowcount > 0


def find_employee(empid: int) -> Optional[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select e.empid, e.hire_date, p.personid, p.dni, p.name, p.last_name,
                       p.email, p.address, p.phone
                from employee e
                join person p on p.personid = e.personid
                where e.empid = %s
                """,
                (empid,),
            )
            return cursor.fetchone()


def update_employee(empid: int, hire_date: str, dni: str, name: str, last_name: str, email: str, address: str, phone: str) -> bool:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                update employee e
                set hire_date = %s
                from person p
                where e.empid = %s and p.personid = e.personid
                """,
                (hire_date, empid),
            )
            if cursor.rowcount == 0:
                return False
            cursor.execute(
                """
                update person p
                set dni = %s, name = %s, last_name = %s, email = %s, address = %s, phone = %s
                from employee e
                where e.empid = %s and p.personid = e.personid
                """,
                (dni, name, last_name, email, address, phone, empid),
            )
            return True


def deactivate_employee(empid: int) -> bool:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                "update person set status = 'I' where personid = (select personid from employee where empid = %s)",
                (empid,),
            )
            return cursor.rowcount > 0


def list_active_employees() -> Iterator[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select e.empid, p.personid, p.dni, p.name, p.last_name,
                       p.email, p.phone
                from employee e
                join person p on p.personid = e.personid
                where p.status <> 'I'
                order by p.last_name, p.name, e.empid
                """
            )
            yield from cursor.fetchall()


def find_client(clientid: int) -> Optional[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select c.clientid, c.ruc, p.personid, p.dni, p.name, p.last_name,
                       p.email, p.address, p.phone
                from client c
                join person p on p.personid = c.personid
                where c.clientid = %s
                """,
                (clientid,),
            )
            return cursor.fetchone()


def update_client(clientid: int, ruc: str, dni: str, name: str, last_name: str, email: str, address: str, phone: str) -> bool:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute("update client set ruc = %s where clientid = %s", (ruc, clientid))
            if cursor.rowcount == 0:
                return False
            cursor.execute(
                """
                update person p
                set dni = %s, name = %s, last_name = %s, email = %s, address = %s, phone = %s
                from client c
                where c.clientid = %s and p.personid = c.personid
                """,
                (dni, name, last_name, email, address, phone, clientid),
            )
            return True


def deactivate_client(clientid: int) -> bool:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                "update person set status = 'I' where personid = (select personid from client where clientid = %s)",
                (clientid,),
            )
            return cursor.rowcount > 0

def insert_appuser(username:str, password:str, role:str, dni:str) -> None:
    with get_connection() as connection:
        with connection.cursor() as cursor:
           cursor.execute(
                """
                select e.empid from person p, employee e  where p.dni=%s and e.personid  =p.personid
                """,
                (dni,),
            )
           empid = cursor.fetchone()["empid"]
           cursor.execute(
                """
                insert into app_user(username, password, role, empid)
                values (%s, %s, %s, %s)
                """,
                (username, password, role, empid),
            )

def find_service_price(connection: psycopg.Connection, serviceid: int) -> Optional[dict]:
    with connection.cursor() as cursor:
        cursor.execute(
            """
            select serviceid, price::numeric as price
            from services
            where serviceid = %s and status = true
            """,
            (serviceid,),
        )
        return cursor.fetchone()


def find_product_price(connection: psycopg.Connection, productid: int) -> Optional[dict]:
    with connection.cursor() as cursor:
        cursor.execute(
            """
            select productid, price::numeric as price
            from product
            where productid = %s and status <> 'I'
            for update
            """,
            (productid,),
        )
        return cursor.fetchone()


def insert_invoice_header(
    connection: psycopg.Connection,
    code: str,
    payment_method: str,
    total: object,
    status: str,
    clientid: Optional[int],
    appoid: Optional[int],
) -> int:
    with connection.cursor() as cursor:
        cursor.execute(
            """
            insert into invoice_header(code, payment_method, total, status, clientid, appoid)
            values (%s, %s, %s, %s, %s, %s)
            returning inv_heaid
            """,
            (code, payment_method, total, status, clientid, appoid),
        )
        return cursor.fetchone()["inv_heaid"]


def insert_invoice_detail(
    connection: psycopg.Connection,
    inv_heaid: int,
    serviceid: Optional[int],
    productid: Optional[int],
    quantity: int,
    unit_price: object,
    total: object,
) -> None:
    with connection.cursor() as cursor:
        cursor.execute(
            """
            insert into invoice_details(inv_heaid, serviceid, productid, quantity, unit_price, total)
            values (%s, %s, %s, %s, %s, %s)
            """,
            (inv_heaid, serviceid, productid, quantity, unit_price, total),
        )


def list_invoices() -> Iterator[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select ih.inv_heaid, ih.code, ih.payment_method, ih.total::float8 as total,
                       ih.status, ih.clientid, ih.appoid,
                       p.name as client_name, p.last_name as client_last_name
                from invoice_header ih
                left join client c on c.clientid = ih.clientid
                left join person p on p.personid = c.personid
                order by ih.inv_heaid desc
                """
            )
            yield from cursor.fetchall()


def find_invoice(inv_heaid: int) -> Optional[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select ih.inv_heaid, ih.code, ih.payment_method, ih.total::float8 as total,
                       ih.status, ih.clientid, ih.appoid,
                       p.name as client_name, p.last_name as client_last_name
                from invoice_header ih
                left join client c on c.clientid = ih.clientid
                left join person p on p.personid = c.personid
                where ih.inv_heaid = %s
                """,
                (inv_heaid,),
            )
            invoice = cursor.fetchone()
            if invoice is None:
                return None
            cursor.execute(
                """
                  select id.serviceid, id.productid, id.quantity,
                       id.unit_price::float8 as unit_price, id.total::float8 as total,
                       s.name as service_name, pr.name as product_name
                from invoice_details id
                left join services s on s.serviceid = id.serviceid
                left join product pr on pr.productid = id.productid
                where id.inv_heaid = %s
                order by id.serviceid nulls last, id.productid nulls last
                """,
                (inv_heaid,),
            )
            invoice["details"] = cursor.fetchall()
            return invoice

# ---- Ingresar citas 
def insert_appointment(date:str, start_time:time,end_time:time, description:str,status:str, empid:int, clientid:int,)-> None:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                insert into appointments(date, start_time, end_time, description,status, empid, clientid)
                values (%s,%s,%s,%s,%s,%s,%s)
                """,
                (date, start_time, end_time, description, status, empid, clientid),
            )


def list_active_appointments() -> Iterator[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select a.appoid, a.date, a.start_time, a.end_time, a.description,
                       a.status, a.empid, a.clientid,
                       ep.name as employee_name, ep.last_name as employee_last_name,
                       cp.name as client_name, cp.last_name as client_last_name
                from appointments a
                join employee e on e.empid = a.empid
                join person ep on ep.personid = e.personid
                join client c on c.clientid = a.clientid
                join person cp on cp.personid = c.personid
                where a.status <> 'I'
                order by a.date, a.start_time, a.appoid
                """
            )
            yield from cursor.fetchall()


def update_appointment(appoid: int, date: str, start_time: str, end_time: str, description: str, appointment_status: str, empid: int, clientid: int) -> bool:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                update appointments
                set date = %s, start_time = %s, end_time = %s, description = %s,
                    status = case when status = 'F' then 'F' else %s end,
                    empid = %s, clientid = %s
                where appoid = %s and status <> 'I'
                """,
                (date, start_time, end_time, description, appointment_status, empid, clientid, appoid),
            )
            return cursor.rowcount > 0

def update_appointment_status(appoid: int, appointment_status: str) -> bool:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                update appointments
                set status = %s
                where appoid = %s and status in ('P', 'A')
                """,
                (appointment_status, appoid),
            )
            return cursor.rowcount > 0


def deactivate_appointment(appoid: int) -> bool:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute("update appointments set status = 'I' where appoid = %s and status in ('P', 'A')", (appoid,))
            return cursor.rowcount > 0

def login(username:str, password:str) -> Optional[dict]:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                select au.username, au."password" , au.role, e.empid, p.personid, p.name, p.last_name
                from app_user au
                join employee e on e.empid = au.empid
                join person p on p.personid = e.personid
                where au.username = %s
                """,
                (username,),
            )
            return cursor.fetchone()
            
        